import ContactForm from "./components/requestForm";

import './globals.css'

import { Inter } from "next/font/google";
import NavBar from "./components/navbar";
import HomePageGallery from "./components/gallery/homepage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title:
    "Sphere Remodeling | Las Vegas-Henderson Home Remodeling and Renovation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <NavBar />
        {children}


        </body>
    </html>
  );
}
